package enu;

import java.util.EnumSet;

public enum ENUM_COMMAND {

	CONNECT_WEB_SITE("connectWebSite", ENUM_ROLE_VALIDATION_PARAMETER.FIRST_NULL_OR_URL),
	GET_WEB_SITE("getWebSite", ENUM_ROLE_VALIDATION_PARAMETER.TWO_NULL),
	SEARCH_BY_ID("searchById", ENUM_ROLE_VALIDATION_PARAMETER.FIRST_MANDATORY),
	SEARCH_BY_TAG("searchByTag", ENUM_ROLE_VALIDATION_PARAMETER.FIRST_MANDATORY),
	SEARCH_BY_CLASS("searchByClass", ENUM_ROLE_VALIDATION_PARAMETER.FIRST_MANDATORY),
	SEARCH_BY_SELECT("select", ENUM_ROLE_VALIDATION_PARAMETER.FIRST_MANDATORY),
	GET_VALUE_ATTRIBUTE("getValueAttribute", ENUM_ROLE_VALIDATION_PARAMETER.FIRST_MANDATORY),
	GET_FIRST("first", ENUM_ROLE_VALIDATION_PARAMETER.TWO_NULL),
	GET_TEXT("text", ENUM_ROLE_VALIDATION_PARAMETER.TWO_NULL),
	GET_HTML("html", ENUM_ROLE_VALIDATION_PARAMETER.TWO_NULL),
	EQUALS("equals", ENUM_ROLE_VALIDATION_PARAMETER.FIRST_MANDATORY),
	CONTAINS("contains", ENUM_ROLE_VALIDATION_PARAMETER.FIRST_MANDATORY),
	EQUALS_IGNORE_CASE("equalsIgnoreCase", ENUM_ROLE_VALIDATION_PARAMETER.FIRST_MANDATORY),
	EQUALS_IGNORE_SPECIAL_CARACTER("equalsIgnoreSpecialCaracter", ENUM_ROLE_VALIDATION_PARAMETER.FIRST_MANDATORY),
	EQUALS_REGULAR_EXPRESSION("equalsRegularExpression", ENUM_ROLE_VALIDATION_PARAMETER.FIRST_MANDATORY),
	REPLACE_ALL("replaceAll", ENUM_ROLE_VALIDATION_PARAMETER.FIRST_MANDATORY),
	RETURN("return", ENUM_ROLE_VALIDATION_PARAMETER.TWO_NULL),
	GET_RESULT_STEP("getResultStep", ENUM_ROLE_VALIDATION_PARAMETER.FIRST_NUMBER_SECOND_DOMAIN),
	;
	
	private String _xmlCommand;
	private ENUM_ROLE_VALIDATION_PARAMETER _enuRole;

	public final String getXmlCommand() {
		return _xmlCommand;
	}

	public final ENUM_ROLE_VALIDATION_PARAMETER getEnuRole() {
		return _enuRole;
	}

	public static ENUM_COMMAND getEnuCommand(String xmlCommand){
		for (ENUM_COMMAND item : EnumSet.allOf(ENUM_COMMAND.class)) {
			if (item.getXmlCommand().equals(xmlCommand))
				return item;
		}
		return null;
	}

	ENUM_COMMAND(String xmlCommand, ENUM_ROLE_VALIDATION_PARAMETER enuRole){
		this._xmlCommand = xmlCommand;
		this._enuRole = enuRole;
	}
}
